### ISSUE TITLE
invalid command in docker image after fock build

### ISSUE THREAD

**Issue by jbayer** [CloudCredo/cloudrocker#2]
running `fock build` on a simple spring boot `app.groovy` results in an invalid command entry in the docker image.

```
"Cmd": [
            "/bin/sh",
            "-c",
            "#(nop) CMD [/bin/sh -c [\"/bin/bash\", \"/app/cloudfocker-start-1c4352a23e52040ddb1857d7675fe3cc.sh\", \"/app\", \"JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre\", \"JAVA_OPTS=\"-Djava.io.tmpdir=/app/tmp\", \"-XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh\", \"-XX:MaxMetaspaceSize=64M\", \"-XX:MetaspaceSize=64M\"\", \"SERVER_PORT=8080\", \"$PWD/.java-buildpack/spring_boot_cli/bin/spring\", \"run\", \"app.groovy\"]]"
        ]
```

the full detail is here: https://gist.github.com/jbayer/f834e5a08e32bf68519f#file-gistfile1-txt-L50

simple `app.groovy` is here:
```
@Controller
class ThisWillActuallyRun {

    @RequestMapping("/")
    @ResponseBody
    String home() {
        return "BLUE"
    }

    @RequestMapping("/services")
    @ResponseBody
    String services() {
        return System.getenv("VCAP_SERVICES")
    }

}
```

**Comment by hatofmonkeys** [comment]
Tracking this at https://www.pivotaltracker.com/story/show/92253058

**Comment by hatofmonkeys** [comment]
I'm seeing quite a few issues related to "interesting" run commands after image creation, ie:

https://www.pivotaltracker.com/story/show/92817418
https://www.pivotaltracker.com/story/show/92817424

I'm travelling over the next few days so should planning to get to the bottom of this.

**Comment by hatofmonkeys** [comment]
Fixed when we started escaping quotes in run commands. Pesky Java options!
