### ISSUE TITLE
go sample does not fock build

### ISSUE THREAD

**Issue by jbayer** [CloudCredo/cloudrocker#3]
$ fock build
Starting the CloudFocker container...
Running Buildpacks...
-------> Buildpack version 1.1.0
 !     A .godir is required. For instructions:
 !     http://mmcgrana.github.io/2012/09/getting-started-with-go-on-heroku
Started the CloudFocker container.
Deleting the CloudFocker container...
cloudfocker-staging
Deleted container.
2014/12/13 19:38:34  Staging failed - have you added a buildpack for this type of application?
vagrant@ubuntu-14:/vagrant/sample-apps/go$ fock buildpacks
go-buildpack
java-buildpack

**Comment by hatofmonkeys** [comment]
I think this is another issue related to https://www.pivotaltracker.com/story/show/92252742 .

**Comment by hatofmonkeys** [comment]
Fixed in https://github.com/CloudCredo/cloudrocker/commit/ebfe01cd1adecaca99d69d2074eaaef5f0bfde50 .
