### ISSUE TITLE
had to create /app/tmp directory in docker image to get php sample to work

### ISSUE THREAD

**Issue by jbayer** [CloudCredo/cloudrocker#5]
here are some command outputs from the `fock build` image. note the error:
mkfifo: cannot create fifo `/app/tmp/heroku.waitpipe-8080.fycbjO': No such file or directory"
and the mkdir command and then see it working.

     vcap@b3033f667ef4:~$ source ./.profile.d/php.sh
     vcap@b3033f667ef4:~$ /bin/bash cloudfocker-start-1c4352a23e52040ddb1857d7675fe3cc.sh /app vendor/bin/heroku-php-apache2
     Booting on port 8080...
     Using PHP-FPM configuration file 'vendor/heroku/heroku-buildpack-php/conf/php/php-fpm.conf'
     Using PHP configuration (php.ini) file 'vendor/heroku/heroku-buildpack-php/conf/php/php.ini'
     Using Apache2 VirtualHost-level configuration include 'vendor/heroku/heroku-buildpack-php/conf/apache2/default_include.conf'
     Using Apache2 configuration file 'vendor/heroku/heroku-buildpack-php/conf/apache2/heroku.conf'
     mkfifo: cannot create fifo `/app/tmp/heroku.waitpipe-8080.fycbjO': No such file or directory
     vcap@b3033f667ef4:~$ mkdir /app/tmp
     vcap@b3033f667ef4:~$ /bin/bash cloudfocker-start-1c4352a23e52040ddb1857d7675fe3cc.sh /app vendor/bin/heroku-php-apache2
     Booting on port 8080...
     Using PHP-FPM configuration file 'vendor/heroku/heroku-buildpack-php/conf/php/php-fpm.conf'
     Using PHP configuration (php.ini) file 'vendor/heroku/heroku-buildpack-php/conf/php/php.ini'
     Using Apache2 VirtualHost-level configuration include 'vendor/heroku/heroku-buildpack-php/conf/apache2/default_include.conf'
     Using Apache2 configuration file 'vendor/heroku/heroku-buildpack-php/conf/apache2/heroku.conf'
     Starting log redirection...
     Starting php-fpm...
     Starting httpd...
     [14-Dec-2014 08:16:47] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
     [14-Dec-2014 08:16:47] NOTICE: fpm is running, pid 131
     [14-Dec-2014 08:16:47] NOTICE: ready to handle connections
     127.0.0.1 - - [14/Dec/2014:08:17:49 +0000] "GET / HTTP/1.1" 200 65 "-" "curl/7.19.7 (x86_64-pc-linux-gnu) libcurl/7.19.7 OpenSSL/0.9.8k zlib/1.2.3.3 libidn/1.15"

**Comment by hatofmonkeys** [comment]
Tracking at https://www.pivotaltracker.com/story/show/92253168 .

**Comment by hatofmonkeys** [comment]
Should be fixed in https://github.com/CloudCredo/cloudrocker/commit/593d1d938a4fc46d1189fc3c1497bb31ddd3b504
