### ISSUE TITLE
Files beginning with a . in the application root are ignored

### ISSUE THREAD

**Issue by rkoster** [CloudCredo/cloudrocker#7]
While I was testing the [multi-buildpack](https://github.com/ddollar/heroku-buildpack-multi) I run into an issue where it would not be detected. 
After further investigation I found the problem was related to the `.buildpacks` file which was not copied into the staging environment.
I suspect it being related to [these lines](https://github.com/CloudCredo/cloudrocker/blob/master/focker/focker.go#L144-L145).

**Comment by hatofmonkeys** [comment]
Hi Ruben

Sorry for the delay! Hoping to tackle it this weekend. Tracking it here https://www.pivotaltracker.com/story/show/92252742 .

Colin

**Comment by rkoster** [comment]
No problem thanks for sharing the link to the issue

**Comment by hatofmonkeys** [comment]
Fixed in https://github.com/CloudCredo/cloudrocker/commit/ebfe01cd1adecaca99d69d2074eaaef5f0bfde50 .

Hope to meet you at CF Summit Ruben!

**Comment by rkoster** [comment]
@hatofmonkeys thanks, will not be at CF Summit this year, just became a dad for the second time.
