### ISSUE TITLE
404 for https://s3.amazonaws.com/cloudrocker/vagrantboxes/cloudrocker-0.0.2-vbox.box

### ISSUE THREAD

**Issue by BinaryTweedDeej** [CloudCredo/cloudrocker#9]
Hi,

I'm trying to do the `vagrant provision` and getting a 404 when trying to download the vbox: https://s3.amazonaws.com/cloudrocker/vagrantboxes/cloudrocker-0.0.2-vbox.box

Trying it in a browser also yields a 404.

**Comment by hatofmonkeys** [comment]
Hi Dan,

That's probably for the best, the old boxes are now out of date. I'll be building new boxes tomorrow and publishing.

Note - this was caused by a global sed from focker to rocker. Undo the sed if you want a 200 from that URL; just don't use the box.

C

**Comment by hatofmonkeys** [comment]
Hi Dan,

The 0.0.3 version should suit your needs just fine.

C

**Comment by BinaryTweedDeej** [comment]
Ta!
